<?php
/** @package Consultorio::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ConsultaMap.php");

/**
 * ConsultaDAO provides object-oriented access to the Consulta table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Consultorio::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ConsultaDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var date */
	public $Datacon;

	/** @var int */
	public $MedicoId;

	/** @var int */
	public $PacienteId;


	/**
	 * Returns the foreign object based on the value of MedicoId
	 * @return Medico
	 */
	public function GetMedicoMedico()
	{
		return $this->_phreezer->GetManyToOne($this, "Consulta_ibfk_1");
	}

	/**
	 * Returns the foreign object based on the value of PacienteId
	 * @return Paciente
	 */
	public function GetPacientePaciente()
	{
		return $this->_phreezer->GetManyToOne($this, "Consulta_ibfk_2");
	}


}
?>