<?php
/** @package Consultorio::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("MedicoMap.php");

/**
 * MedicoDAO provides object-oriented access to the Medico table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Consultorio::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class MedicoDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Nome;

	/** @var string */
	public $Tel;

	/** @var string */
	public $Especialidade;


	/**
	 * Returns a dataset of Consulta objects with matching MedicoId
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetMedicoConsultas($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "Consulta_ibfk_1", $criteria);
	}


}
?>