<?php
/** @package Consultorio::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("PacienteMap.php");

/**
 * PacienteDAO provides object-oriented access to the Paciente table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Consultorio::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class PacienteDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Nome;

	/** @var string */
	public $Tel;

	/** @var char */
	public $Sexo;

	/** @var int */
	public $Idade;


	/**
	 * Returns a dataset of Consulta objects with matching PacienteId
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetPacienteConsultas($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "Consulta_ibfk_2", $criteria);
	}


}
?>